### ISSUE TITLE
If remote branch is not configured, received unhandled exception

### ISSUE THREAD

**Issue by doppleware** [QualiSystemsLab/colony-cli#20]
STR:
Initialize git repo locally and develop a blueprint, don't connect to remote repo yet, try to use bp validate.
Expected behavior: Message "Local repository not connected to the remote space repository"
Error:
PS C:\Users\ronid\projects\clitest\blueprints> colony bp validate test
Traceback (most recent call last):
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ronid\AppData\Local\Programs\Python\Python39\Scripts\colony.exe\__main__.py", line 7, in <module>
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\site-packages\colony\shell.py", line 96, in main
    command.execute()
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\site-packages\colony\commands\base.py", line 38, in execute
    actions_table[action]()
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\site-packages\colony\commands\bp.py", line 44, in do_validate
    repo, working_branch, temp_working_branch = figure_out_branches(branch, blueprint_name)
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\site-packages\colony\branch_utils.py", line 66, in figure_out_branches
    examine_blueprint_working_branch(repo, blueprint_name=blueprint_name)
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\site-packages\colony\branch_utils.py", line 28, in examine_blueprint_working_branch
    if not repo.current_branch_exists_on_remote():
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\site-packages\colony\utils.py", line 38, in current_branch_exists_on_remote
    remote_branches = self._get_remote_branches_names()
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\site-packages\colony\utils.py", line 108, in _get_remote_branches_names
    return [ref.remote_head for ref in self.remote().refs]
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\site-packages\git\repo\base.py", line 325, in remote
    r = Remote(self, name)
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\site-packages\git\remote.py", line 418, in __init__
    dir(self)
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\site-packages\git\remote.py", line 430, in __getattr__
    return self._config_reader.get(attr)
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\site-packages\git\config.py", line 127, in <lambda>
    return lambda *args, **kwargs: self._call_config(attr, *args, **kwargs)
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\site-packages\git\config.py", line 133, in _call_config
    return getattr(self._config, method)(self._section_name, *args, **kwargs)
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\site-packages\git\config.py", line 82, in assure_data_present
    return func(self, *args, **kwargs)
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "c:\users\ronid\appdata\local\programs\python\python39\lib\configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'remote "origin"'

**Comment by qualidan** [comment]
@doppleware , @ddovbii 

I think this is not handled correctly in utils.py:

    def current_branch_exists_on_remote(self) -> bool:
        local_branch_name = self.active_branch.name
        remote_branches = self._get_remote_branches_names()

self._get_remote_branches_names() should be under a try and return false if there is an exception

**Comment by ddovbii** [comment]
@doppleware, @alexazarh, @qualidan I've pushed some fix, but then I've just realized that probably we should not even allow a user to work in a fresh, just initiated git folder without configured remotes. So, before doing any git magic we need to show some exception like : Bad Blueprint repo since its remotes haven't been set up yet.
What do you think?

**Comment by alexazarh** [comment]
@ddovbii I agree. 
We need to show an error message like the expected behavior in the issue description: "Local repository not connected to the remote space repository".
Unless the branch flag is specified, and in this case we need to allow the operation.
